fix: 修复因默认值导致过期属性合并异常问题
NeteaseYanxuan/OSSA pull request #124
Opened 2022-12-24 10:39 UTC by kiner-tang

**这个 PR 做了什么?** (简要描述所做更改)

- fix: 修复因默认值导致过期属性合并异常问题 #123 

**这个 PR 是什么类型?** (至少选择一个)

- [X] 错误修复(Bugfix) fix #{issue id}
- [ ] 新功能(Feature) resolve #{issue id}
- [ ] 代码重构(Refactor)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 类型描述更新(TypeScript definition update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 未涉及平台修改
- [X] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-12-25 06:26 UTC, CaedmonW requested changes
这里应该也有问题，另外`mergedReadonly`的`waringInfo`取值有点问题
https://github.com/NeteaseYanxuan/OSSA/blob/6573fb0252474410726b44fd09875d8ccbf38414/packages/ossa/src/components/input/index.tsx#L55-L64


还有这里
https://github.com/NeteaseYanxuan/OSSA/blob/6573fb0252474410726b44fd09875d8ccbf38414/packages/ossa/src/components/nav-bar/index.tsx#L143-L147

2022-12-25 06:26 UTC, CaedmonW commented on packages/ossa/src/utils/index.ts
> +    return  res;
```suggestion
return newProp ?? oldProp ?? waringInfo?.defaultVal
```
这样是不是更简洁些？

另外，`defaultVal` 放在 `waringInfo` 中传入，从语义上是不是不太对？

2022-12-25 06:26 UTC, CaedmonW commented on packages/ossa/src/components/modal/index.tsx
> +    closable,
这个单词好像拼错了，目前应该是影响了两个版本，建议直接整体改了修复

2022-12-25 06:45 UTC, kiner-tang commented on packages/ossa/src/components/modal/index.tsx
> +    closable,
那个单词？`closable `吗？这个单词就是可关闭的意思呀

2022-12-25 06:53 UTC, kiner-tang commented on packages/ossa/src/utils/index.ts
> +    return  res;
done

2022-12-26 02:11 UTC, CaedmonW commented on packages/ossa/src/components/modal/index.tsx
> +    closable,
目前项目里已经有`closeable`的拼写，虽然两个意思都对，还是保持统一一下，使用`closeable`来表示可关闭的意思吧

2022-12-26 03:05 UTC, kiner-tang commented on packages/ossa/src/components/modal/index.tsx
> +    closable,
<img width="630" alt="image" src="https://user-images.githubusercontent.com/10286961/209494486-a61cfbd7-cabd-453b-8952-b173afedac39.png">
`closeable`才是拼写错误吧，连翻译都翻译不出来
<img width="503" alt="image" src="https://user-images.githubusercontent.com/10286961/209494525-c2e5f1b5-c216-4f7f-aba1-834ae4f818a6.png">

2022-12-26 06:49 UTC, CaedmonW commented on packages/ossa/src/components/modal/index.tsx
> +    closable,
两个应该都是可用的，把`closeable`统一成`closable`的影响更大，所以还是改`closable`吧
https://www.collinsdictionary.com/dictionary/english/closable
![image](https://user-images.githubusercontent.com/107974245/209512645-427b3511-a015-42f6-a6c0-2695a954412e.png)

https://www.merriam-webster.com/dictionary/closeable
![image](https://user-images.githubusercontent.com/107974245/209512732-3315c227-8861-4678-a8ff-8921de45bd06.png)

https://docs.oracle.com/javase/7/docs/api/java/io/package-summary.html
![image](https://user-images.githubusercontent.com/107974245/209513742-757ad452-634e-482b-94a7-55cb31710534.png)

2022-12-26 07:00 UTC, kiner-tang commented on packages/ossa/src/components/modal/index.tsx
> +    closable,
那我改一下吧，不过通常好像按照拼写规则，closable用的比较多

2022-12-26 12:06 UTC, CaedmonW approved these changes
lgtm

2022-12-27 03:50 UTC, merged