feat(noticeBar): 通知栏自定义滚动时长支持
NeteaseYanxuan/OSSA pull request #78
Opened 2022-11-09 13:39 UTC by kiner-tang

**这个 PR 做了什么?** (简要描述所做更改)

- feat(noticeBar): 通知栏自定义滚动时长支持
- docs: 修改通知栏部分文档错误

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) fix #{issue id}
- [X] 新功能(Feature) resolve #{issue id}
- [ ] 代码重构(Refactor)
- [X] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [X] 类型描述更新(TypeScript definition update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] 未涉及平台修改
- [X] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-11-14 02:21 UTC, CaedmonW requested changes

2022-11-14 02:25 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +    'WebkitAnimationDuration': `${mergedDuration}s`,
我看之前虽然文档中有说明`speed`属性，但实际上并没有实现相关的逻辑，那么，我们预期的`speed`属性的效果是怎样的呢？`speed`属性所给的值代表的是整段文本在多长时间内的滚动速度呢？

2022-11-14 02:37 UTC, CaedmonW commented on packages/ossa/src/components/noticeBar/index.tsx
> +    'WebkitAnimationDuration': `${mergedDuration}s`,
`speed`属性应该是参考了`taro-ui`的属性设计，但是当时却没有实现
想要实现的效果应该是用于控制文字滚动速度，设定该值后，文字滚动速度不应该和文案长度相关。实际使用中，文案内容往往是动态的，如果业务中文案长度变化范围较大，对用户侧来说，通知栏的体验会不一致。

2022-11-14 02:55 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +    'WebkitAnimationDuration': `${mergedDuration}s`,
恩恩，确实是这样，我找时间参考一下其他组件库的设计，实现一下`speed`的逻辑吧

2022-11-14 04:01 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +    'WebkitAnimationDuration': `${mergedDuration}s`,
感觉咱们可以直接引入这个库处理文字滚动的逻辑，我看很多`react`UI库都使用这个

- https://www.npmjs.com/package/react-fast-marquee

2022-11-15 01:49 UTC, CaedmonW commented on packages/ossa/src/components/noticeBar/index.tsx
> +    'WebkitAnimationDuration': `${mergedDuration}s`,
可以试试看，需要看下其他端小程序的表现是否符合预期

2022-11-17 02:38 UTC, CaedmonW requested changes
目前`scrollable`属性好像失效了

另外，目前`Marquee`内部实现使用的是div标签，在打包之后，div标签依旧存在，而taro支持html标签是从[3.3版本开始](https://docs.taro.zone/docs/use-h5)的，感觉需要验证下老版本taro的支持度
![image](https://user-images.githubusercontent.com/107974245/202340876-750e26ef-ce4d-445f-80ab-8d79a1c834e0.png)

2022-11-17 02:45 UTC, kiner-tang commented
> 目前`scrollable`属性好像失效了
> 
> 另外，目前`Marquee`内部实现使用的是div标签，在打包之后，div标签依旧存在，而taro支持html标签是从[3.3版本开始](https://docs.taro.zone/docs/use-h5)的，感觉需要验证下老版本taro的支持度 ![image](https://user-images.githubusercontent.com/107974245/202340876-750e26ef-ce4d-445f-80ab-8d79a1c834e0.png)

好的，我抽空优化并验证一下，最近比较忙

2022-11-20 13:46 UTC, kiner-tang commented
> > 目前`scrollable`属性好像失效了
> > 另外，目前`Marquee`内部实现使用的是div标签，在打包之后，div标签依旧存在，而taro支持html标签是从[3.3版本开始](https://docs.taro.zone/docs/use-h5)的，感觉需要验证下老版本taro的支持度 ![image](https://user-images.githubusercontent.com/107974245/202340876-750e26ef-ce4d-445f-80ab-8d79a1c834e0.png)
> 
> 好的，我抽空优化并验证一下，最近比较忙

既然这些框架没有现成的同时支持小程序和h5的逻辑，那么我们就自己实现自定义滚动的逻辑吧。传入的速度`speed`与内容宽度计算可以得出我们滚动一屏所需要的时间，通过这个时间设置动画播放的时间。

2022-11-22 01:50 UTC, CaedmonW commented
> 既然这些框架没有现成的同时支持小程序和h5的逻辑，那么我们就自己实现自定义滚动的逻辑吧。传入的速度speed与内容宽度计算可以得出我们滚动一屏所需要的时间，通过这个时间设置动画播放的时间。

动态获取内容的宽度做计算，我觉得可行

2022-11-22 03:39 UTC, CaedmonW commented on packages/ossa/src/components/noticeBar/index.tsx
> +  });
在小程序中，`useEffect`中触发，并不能保证一定可以获取到元素实例，所以一般需要在`nextTick`中触发或者使用`settimeout`，最好也兼容下`res`为空的报错

2022-11-23 06:48 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +  });
好的

2022-11-23 06:49 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +    });
有道理

2022-11-24 02:25 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +  });
done

2022-11-24 02:25 UTC, kiner-tang commented on packages/ossa/src/components/noticeBar/index.tsx
> +    });
done

2022-11-24 02:34 UTC, CaedmonW approved these changes

2022-11-24 02:35 UTC, CaedmonW commented
lgtm 👍

2022-11-24 02:36 UTC, merged

2022-11-24 03:07 UTC, CaedmonW commented
![noticebar Testing -- Notice Normal Testing -- case #3 自定义滚动速度通知栏框 (failed)](https://user-images.githubusercontent.com/107974245/203685054-d18f80c2-9b22-4efe-a81f-c30d556d812a.png)

CI 中的测试，页面中的中文会乱码，导致获取到的宽度有问题，测试用例执行失败了

2022-11-24 03:29 UTC, kiner-tang commented
> ![noticebar Testing -- Notice Normal Testing -- case #3 自定义滚动速度通知栏框 (failed)](https://user-images.githubusercontent.com/107974245/203685054-d18f80c2-9b22-4efe-a81f-c30d556d812a.png)
> 
> CI 中的测试，页面中的中文会乱码，导致获取到的宽度有问题，测试用例执行失败了

咦，怎么中文会变成乱码呢？是不是的解决乱码的问题呀

2022-11-24 03:51 UTC, CaedmonW commented
> 咦，怎么中文会变成乱码呢？是不是的解决乱码的问题呀

理论上解决乱码问题才是正确的解决方案，我上次试了下，好像没有找到解决方案😅
而且乱码还不是必现的

2022-11-24 03:57 UTC, kiner-tang commented
> > 咦，怎么中文会变成乱码呢？是不是的解决乱码的问题呀
> 
> 理论上解决乱码问题才是正确的解决方案，我上次试了下，好像没有找到解决方案😅 而且乱码还不是必现的

那这边临时将自定义滚动的实例的文字改成英文，这样就不会因为乱码导致宽度与实际不一致而用例不通过了

2022-11-24 04:10 UTC, kiner-tang commented
> > 咦，怎么中文会变成乱码呢？是不是的解决乱码的问题呀
> 
> 理论上解决乱码问题才是正确的解决方案，我上次试了下，好像没有找到解决方案😅 而且乱码还不是必现的

感觉应该是基础镜像`ubuntu-latest`不支持中文字符集或者没有设置中文字符集，我有时间也看一下这个问题

2022-11-24 05:34 UTC, CaedmonW commented
> 感觉应该是基础镜像`ubuntu-latest`不支持中文字符集或者没有设置中文字符集，我有时间也看一下这个问题

👍