feat: 新增营销组件ossaui-loki
NeteaseYanxuan/OSSA pull request #87
Opened 2022-11-25 02:07 UTC by EchoHub

**这个 PR 做了什么?** (简要描述所做更改)

新增ossaui-loki营销组件库

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) fix #{issue id}
- [1 ] 新功能(Feature) resolve #{issue id}
- [ ] 代码重构(Refactor)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 类型描述更新(TypeScript definition update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ 1] 未涉及平台修改
- [ ] 所有小程序
- [ ] 微信小程序
- [ ] 支付宝小程序
- [ ] 百度小程序
- [ ] 字节跳动小程序
- [ ] QQ 轻应用
- [ ] 京东小程序
- [ ] 快应用平台（QuickApp）
- [ ] Web 平台（H5）
- [ ] 移动端（React-Native）

2022-11-25 07:20 UTC, jianzhouf requested changes
yarn.lock 工程里不需要，可以删除

2022-11-25 08:06 UTC, CaedmonW requested changes

2022-11-25 08:06 UTC, CaedmonW commented on packages/loki/package-lock.json
> +    "": {
不必要的文件

2022-11-28 06:04 UTC, CaedmonW commented on packages/loki/src/utils/css/index.ts
>    }
这一块的逻辑是不是已经不需要了？

2022-11-28 08:17 UTC, CaedmonW approved these changes

2022-11-28 08:22 UTC, EchoHub commented
> yarn.lock 工程里不需要，可以删除

2022-11-28 09:55 UTC, jianzhouf approved these changes

2022-11-28 09:56 UTC, merged